import React from 'react'
import Head from 'next/head'

// import components
import MainNav from '../components/mainNav'
import Footer from '../components/footer'
import HeroBanner from '../components/heroBanner'
import Services from '../components/services'
import Clients from '../components/clients'
import WorkGrid from '../components/workGrid'

// import & setup styles
import { Inter } from 'next/font/google'
import styles from '../styles/Home.module.css'
const inter = Inter({ subsets: ['latin'] })


import Video from './[video]'


export default function Home() {

  return (
    <>
    <style jsx global>{`
        html {
          font-family: ${inter.style.fontFamily};
        }
      `}</style>
      <Head>
        <title>McM Sound</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#111214" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main} onContextMenu={(e) => { e.preventDefault(); }}>
        <HeroBanner />
        <WorkGrid />
        <Services />
        <Clients />
        <MainNav />
        <Footer />
      </main>
    </>
  )
}